-- Create the scores table for leaderboard persistence
CREATE TABLE IF NOT EXISTS public.scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,
  player TEXT NOT NULL,
  score INTEGER NOT NULL,
  duration_ms INTEGER NOT NULL,
  events_handled INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read leaderboard entries (for SELECT query)
DROP POLICY IF EXISTS "Allow anonymous read" ON public.scores;
CREATE POLICY "Allow anonymous read" ON public.scores
  FOR SELECT USING (true);

-- Allow anyone to submit new scores (for INSERT query)
DROP POLICY IF EXISTS "Allow anonymous insert" ON public.scores;
CREATE POLICY "Allow anonymous insert" ON public.scores
  FOR INSERT WITH CHECK (true);
